<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Добро пожаловать' => 'Добро пожаловать',
    'У вас нет прав!' => 'У вас нет прав!',
    'Эта страница не существует!' => 'Эта страница не существует!',
    'Запись добавлена!' => 'Запись добавлена!',
    'Запись обновлена!' => 'Запись обновлена!',
    'Ваш статус <span class="status_view">активен</span>!' => 'Ваш статус <span class="status_view">активен</span>!',
    'Ваш статус <span class="status_view">не активен</span>!' => 'Ваш статус <span class="status_view">не активен</span>!',
    'Страница не найдена!' => 'Страница не найдена!',
    'Спонсора нет!' => 'Спонсора нет!',
    'Запись обновлена!' => 'Запись обновлена!',
    'Ошибка!' => 'Ошибка!',
    'Platform activated - Активация платформы!' => 'Platform activated - Активация платформы!',
    'Партнер активирован!' => 'Партнер активирован!',
    'Вы зарегистрированы! Можете зайти в Личный Кабинет здесь' => 'Вы зарегистрированы! Можете зайти в Личный Кабинет здесь',
    'Вы зарегистрированы!' => 'Вы зарегистрированы!',
    'Запись удалена!' => 'Запись удалена!',
    'Такой страницы не существует!' => 'Такой страницы не существует!',
    'Тема: Подтверждение регистрации' => 'Тема: Подтверждение регистрации',
    'Вы зарегистрированы! Подверждение регистрации отправлено вам на почту.' => 'Вы зарегистрированы! Подверждение регистрации отправлено вам на почту.',
    'Вы уже зарегистрированы!' => 'Вы уже зарегистрированы!',
    'Вы прошли проверку!' => 'Вы прошли проверку!',
    'Пароль изменен!' => 'Пароль изменен!',
    'Это поле должно быть заполнено!' => 'Это поле должно быть заполнено!',
    'Введенны неправильные символы!' => 'Введенны неправильные символы!',
    'Рассылка создана!' => 'Рассылка создана!',
    'Запрос на вывод совершен!' => 'Запрос на вывод совершен!',
    'Запрос на вывод выслан!' => 'Запрос на вывод выслан!',
    'Партнер добавлен' => 'Партнер добавлен',
    'Партнеры добавлен' => 'Партнеры добавлен',
    'Демо структура создана!' => 'Демо структура создана!',
    'Список обновлен!' => 'Список обновлен!',
    'Ваше сообщение отправлено!' => 'Ваше сообщение отправлено!',
    'Вы активированы!' => 'Вы активированы!',
    '<p>Здравствуйте, <span style="color:#002857;">{first_name}&nbsp;{last_name}</span></p>
	<p>Напоминаем ваши данные, указанные при регистрации:</p>
	<p><b>Login:</b> <span style="color:#002857;">{login}</span></p>
	<p><b>E-mail:</b> <span style="color:#002857;">{email}</span></p>
	<p>Для подтверждения пароля перейдите по ссылке&nbsp;<a href="{site}/confirm/{partner_id}/{auth_key}">{site}/confirm/{partner_id}/{auth_key}</a></p>
	<br/>
	<p>С уважением, служба поддержки. <br/><a  style="color:#002857;" href="{site}">{site}</a></p>' 
		=> 
	'<p>Здравствуйте, <span style="color:#002857;">{first_name}&nbsp;{last_name}</span></p>
	<p>Напоминаем ваши данные, указанные при регистрации:</p>
	<p><b>Login:</b> <span style="color:#002857;">{login}</span></p>
	<p><b>E-mail:</b> <span style="color:#002857;">{email}</span></p>
	<p>Для подтверждения пароля перейдите по ссылке&nbsp;<a href="{site}/confirm/{partner_id}/{auth_key}">{site}/confirm/{partner_id}/{auth_key}</a></p>
	<br/>
	<p>С уважением, служба поддержки. <br/><a  style="color:#002857;" href="{site}">{site}</a></p>',
];
