<?php
return [
    'adminEmail' => 'support@traffic-profit.com',
    'supportEmail' => 'support@traffic-profit.com',
    'email_from' => 'traffic-profit.com',
    'site_url' => 'traffic-profit.com',
    'brand_slogan' => '',
    'user.passwordResetTokenExpire' => 3600,
    'payeer' => [
		'merchant_id' => 791740633,
		'account_number' => 'P1012433034',
		'currency' =>'USD',
		'success_url' => 'https://traffic-profit.com/payeer/success-payment',
		'fail_url' => 'https://traffic-profit.com/payeer/failure-payment',
		'status_url' => 'https://traffic-profit.com/payeer/status-payment',
		'secret_key' =>'wiK2ymG9ipO53RsG',
		'cipher_key' =>'ZyE2Aj988ZvXgQer',
		'payeer_ips' =>['185.71.65.92', '185.71.65.189', '149.202.17.210'],
		'api_id' =>'',
		'api_name' =>'',
		'api_ip' =>'',
		'api_secret_key' =>'',
	],
	'controllers' => [
		1=>['table'=>'admin_menu', 'model'=>'AdminMenu', 'controller'=>'AdminMenu', 'name'=>Yii::t('form', 'Админ меню')],
		2=>['table'=>'pagination', 'model'=>'Pagination', 'controller'=>'Pagination', 'name'=>Yii::t('form', 'Пагинация')],
		3=>['table'=>'permissions', 'model'=>'Permissions', 'controller'=>'Permissions', 'name'=>Yii::t('form', 'Права доступа')],
		4=>['table'=>'user', 'model'=>'Users', 'controller'=>'Users', 'name'=>Yii::t('form', 'Пользователи')],
		5=>['table'=>'user_groups', 'model'=>'UserGroups', 'controller'=>'UserGroups', 'name'=>Yii::t('form', 'Группы пользователей')],
		6=>['table'=>'menu', 'model'=>'Menu', 'controller'=>'Menu', 'name'=>Yii::t('form', 'Меню')],
		7=>['table'=>'content', 'model'=>'Content', 'controller'=>'Content', 'name'=>Yii::t('form', 'Контент')],
		8=>['table'=>'static_content', 'model'=>'StaticContent', 'controller'=>'StaticContent', 'name'=>Yii::t('form', 'Статичный контент')],
		9=>['table'=>'menu_categories', 'model'=>'MenuCategories', 'controller'=>'MenuCategories', 'name'=>Yii::t('form', 'Тип меню')],
		10=>['table'=>'partners', 'model'=>'Partners', 'controller'=>'Partners', 'name'=>Yii::t('form', 'Партнеры')],
		11=>['table'=>'matrix_payments', 'model'=>'MatrixPayments', 'controller'=>'BackendAccounting', 'name'=>Yii::t('form', 'Бухгалтерия')],
	],
	'content_controllers' => [7],
	'content_controller' => 7,
	'menu_controllers' => [7,8],
	'permitted_pages' => ['users/profile'],
	'backend_dir' => 'backend',
	'upload_dir' => [],
	'valid_image_types'=>["gif", "jpg", "jpeg", "png"],
	'image_size_limit'=>10,
	'pagination'=>['default' => 20, 'backend-partners'=>100],
	'admin_top_menu' =>[],
	'admin_left_menu' =>[],
	'menu_category' =>['front_top'=>1, 'front_left'=>2, 'front_bottom_1'=>3, 'front_bottom_2'=>4, 'front_bottom_3'=>5, 'backoffice_left'=>6, 'backoffice_top'=>7],
	/*'captcha_site_key'=>'6LdFWYEUAAAAAFcToFyb6-2lvxojkwbR3-qCMe4L',
	'captcha_secret'=>'6LdFWYEUAAAAAHCFu6Yn3wlcRjHQk0B_MBy78_Ht',*/
	'structure_levels'=>5,
	'matrices_count'=>8,
	'matrices_linear_count'=>6,
	'matrix_payments'=>[
		1 => ['type' => 1, 'amount'=>0.01], 
		2 => ['type' => 2, 'amount'=>0], 
		3 => ['type' => 2, 'amount'=>0.06], 
		4 => ['type' => 2, 'amount'=>0.16],
		5 => ['type' => 2, 'amount'=>0.8],
		6 => ['type' => 2, 'amount'=>1.82],
		7 => ['type' => 2, 'amount'=>3.9],
		8 => ['type' => 2, 'amount'=>10.4],
	],
	'balls'=>[
		1 => 1000, 
		2 => 2000, 
		3 => 3000, 
		4 => 4000,
		5 => 5000,
		6 => 6000,
		7 => 7000,
		8 => 8000,
	],
	'matrix_places_count'=>[
		1 => 6, 
		2 => 6, 
		3 => 6,
		4 => 6,
		5 => 6,
		6 => 6,
		7 => 6,
		8 => 6,
	],
	'captcha_params'=>[
		'width' => 60, 
		'height' => 22, 
		'height' => 22,
		'bg_color' => [0 => 0, 1 => 0, 2 => 0],
		'text_color' => [0 => 255, 1 => 255, 2 => 255],
		'font_size' => 12,
		'x' => 5,
		'y' => 3,
	],
	'count_down_days' => 200,
	'register_bonus' => 20,
	'register_tokens' => 2000,
	'upload_dir' => [
		'banners_advert'=>['model'=>'AddBannerForm', 'dir'=>'banners', 'alias'=>'banners_advert', 'tmp'=>'tmp', 'uploads'=>'uploads', 'image_sizes'=>['thumbnail'=>['width'=>0, 'height'=>0, 'dir'=>'thumb', 'crop'=>false, 'resize'=>false]]],
		'slider'=>['model'=>'Slider', 'dir'=>'slider', 'alias'=>'slider', 'tmp'=>'tmp', 'uploads'=>'uploads', 'image_sizes'=>['thumbnail'=>['width'=>600, 'height'=>185, 'dir'=>'thumb', 'crop'=>false, 'resize'=>false]]],
		'landings' => ['model'=>'Landings', 'alias'=>'landings', 'tmp'=>'zip', 'tmp_dir'=>'tmp', 'uploads'=>'landings', 'dir'=>'landings', 'zip'=>'zip', 'assets'=>'assets', 'css'=>'css', 'images'=>'images'],
		'sponsor_advert'=>['model'=>'SponsorAdvert', 'uploads'=>'uploads', 'dir'=>'sponsor_advert', 'alias'=>'sponsor_advert', 'tmp'=>'tmp', 'uploads'=>'uploads', 'image_sizes'=>[
			'thumbnail'=>['width'=>468, 'height'=>60, 'dir'=>'thumb', 'crop'=>true, 'resize'=>true], 
			'origin_image'=>['width'=>468, 'height'=>60, 'dir'=>'origin', 'crop'=>true, 'resize'=>true]
		]],
	],
	'landings_dir' => [
		'tmp'=>'tmp', 'landings'=>'landings', 'zip'=>'zip'
	],
	'default_payment_wallet'=>[
		'name'=>Yii::t('form', 'Payeer кошелек'),
		'index'=>'payeer'
	],
	'payments_systems'=>[
		//1 => [Yii::t('form', 'Bitcoin кошелек'), 'blockchain', 'blockchain'], 
		//2 => [Yii::t('form', 'Qiwi кошелек'), 'qiwi_wallet', 'qiwi'], 
		3 => [Yii::t('form', 'Perfect кошелек'), 'perfect_wallet', 'perfect'],
	],
	'payments_types'=>[
		1 => [Yii::t('form', 'Perfect кошелек'), 'perfect_wallet', 'perfect', 'null', '', 'U'],
		2 => [Yii::t('form', 'Advacash кошелек'), 'advcash_wallet', 'advacash', 'common\components\advacash\models\Advacash', '', 'U'],
		3 => [Yii::t('form', 'Payeer кошелек'), 'payeer_wallet', 'payeer', 'common\modules\payeer\models\Payeer', 'default', 'P'],
	],
	'account_types'=>[
		1 => Yii::t('form', 'Оплата'), 
		2 => Yii::t('form', 'Выплата'),
	],
	'withdrawal_statuses'=>[
		0 => Yii::t('form', 'Отклонен'), 
		1 => Yii::t('form', 'На рассмотрении'), 
		2 => Yii::t('form', 'Подтвержден'),
	],
	'partner_statuses'=>[
		0 => Yii::t('form', 'Не подтвержден'), 
		1 => Yii::t('form', 'Подтвержден'), 
		2 => Yii::t('form', 'Партнер'),
		3 => Yii::t('form', 'Лидер'),
		4 => Yii::t('form', 'VIP - лидер'),
		5 => Yii::t('form', 'Инвестор'),
		6 => Yii::t('form', 'Золотой жетон'),
	],
	/*'reserve_statuses'=>[
		2 => Yii::t('form', 'Партнер'),
		3 => Yii::t('form', 'Лидер'),
		4 => Yii::t('form', 'VIP - лидер'),
		5 => Yii::t('form', 'Инвестор'),
		6 => Yii::t('form', 'Золотой жетон'),
	],*/
	'reserve_statuses'=>[
		2 => Yii::t('form', 'Partner'),
		3 => Yii::t('form', 'Leader'),
		4 => Yii::t('form', 'VIP - leader'),
		5 => Yii::t('form', 'Investor'),
		6 => Yii::t('form', 'Gold medal'),
	],
	'bonus_list'=>[
		1 => Yii::t('form', '20$'), 
		2 => Yii::t('form', '50$'),
		3 => Yii::t('form', '100$'),
		4 => Yii::t('form', '200$'),
	],
	'payment_packages'=>[
		'earning'=>[
			1 => 1,
		],
	],
	/*'status_amount'=>[
		50 => 2,
		250 => 3,
		500 => 4,
		750 => 5,
		1000 => 6,
	],*/
	'top_leader_limit' => 10,
	'demo_structure_count' => 1700,
	'demo_structure_type' => false,
	'demo_structure_activation' => false,
	'structure_type' => 2,
	'activation_amount' => 50,
	'activate_matrices'=>[
		'1'=>Yii::t('form', 'Матрица').' 1', 
		'2'=>Yii::t('form', 'Матрица'.' 2'), 
	],
	'level_structure_percentage'=>[
		1 => 10, 
		2 => 5, 
		3 => 2,
		4 => 2,
		5 => 1,
	],
	'structures'=>[
		'1'=>Yii::t('form', 'Короткие матрицы'), 
		/*'2'=>Yii::t('form', 'Глубокие матрицы'), 
		'3'=>Yii::t('form', 'Структура 3'),*/
	],
	'payments_csv_dir'=>[
		'bitcoin',
		'perfect',
		'qiwi',
	],
	'ticket_admin'=>1,
	'faq_type'=>[
		'1'=>Yii::t('form', 'Фронт'), 
		'2'=>Yii::t('form', 'Личный кабинет'), 
	],
	'slider' => ['is_enable'=>true],
	'counter' => ['is_enable'=>false, 'content'=>true, 'date'=>['year'=>2017, 'month'=>11, 'day'=>10]],
	'email_black_list'=>[
		'sample@email.tst',
		'netsparker@example.com'
	],
	'login_white_list'=>[
		'strong',
	],
	'is_action_allowed'=>true,
	'is_payment_allowed'=>false,
	'max_reserve_places'=>100,
	'list_view_count'=>3,
	'update_emails_statuses_list'=>[
		'0'=>Yii::t('form', 'Неактивные'), 
		'1'=>Yii::t('form', 'Активные'), 
	],
	'defaultTheme' => 'hilite',
	'backofficeThemeLayout' => '@app/themes/backoffice-hilite/views/layouts/',
];
