<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
	'<p>Здравствуйте123, <span style="color:#002857;">{first_name}&nbsp;{last_name}</span></p>
	<p>Напоминаем ваши данные, указанные при регистрации:</p>
	<p><b>Login:</b> <span style="color:#002857;">{login}</span></p>
	<p><b>E-mail:</b> <span style="color:#002857;">{email}</span></p>
	<p>Для подтверждения пароля перейдите по ссылке&nbsp;<a href="{site}/confirm/{partner_id}/{auth_key}">{site}/confirm/{partner_id}/{auth_key}</a></p>
	<br/>
	<p>С уважением, служба поддержки. <br/><a  style="color:#002857;" href="{site}">{site}</a></p>' 
		=> 
	'<p>Здравствуйте, <span style="color:#002857;">{first_name}&nbsp;{last_name}</span></p>
	<p>Напоминаем ваши данные, указанные при регистрации:</p>
	<p><b>Login:</b> <span style="color:#002857;">{login}</span></p>
	<p><b>E-mail:</b> <span style="color:#002857;">{email}</span></p>
	<p>Для подтверждения пароля перейдите по ссылке&nbsp;<a href="{site}/confirm/{partner_id}/{auth_key}">{site}/confirm/{partner_id}/{auth_key}</a></p>
	<br/>
	<p>С уважением, служба поддержки. <br/><a  style="color:#002857;" href="{site}">{site}</a></p>',
	'Вход' => 'Вход123'
];
