<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Контент' => 'Content',
    'Администрация' => 'Administration',
    'Вход' => 'Enter',
    'Выход' => 'Exit',
    'Профиль' => 'Profile',
    'Главная' => 'Main',
    'Новости' => 'News',
    'Вывод' => 'Withdrawal',
    'Структура' => 'Structure',
    'Матрицы' => 'Matrices',
    'Статистика' => 'Stats',
    'TOP Leaders' => 'TOP Leaders',
    'Активация' => 'Activation',
    'Ожидаемый заработок' => 'Expected earnings',
    'Реальный заработок' => 'Real earnings',
    'Топ лидерам' => 'For Top leaders',
    'Рекламные материалы' => 'Advertisement materials',
    'Реферальные ссылки' => 'Referral`s links',
    'Баннерная реклама' => 'Banners advertisement',
    'Маркетинг план' => 'Marketing plan',
    'Напишите нам' => 'Support',
    'Редактировать рекламу' => 'Edit adverisement',
    'Регистрация' => 'Registration',
    'ВНИМАНИЕ!<br/>НЕ ИСПОЛЬЗУЙТЕ для Регистрации почту mail.ru, inbox.ru, list.ru, bk.ru, ua, ua.net  - так как вы не сможете подтвердить регистрацию!<br/>Пользуйтесь почтой gmail.com , yahoo.com<br/>' => 'gmail.com, yahoo.com is desirable<br/>',
    'Информация' => 'Info',
    'Запрос' => 'Request',
    'Личный кабинет' => 'Backoffice',
    'Здравствуйте' => 'Hello!',
    'Меню' => 'Menu',
    'Всего заработано' => 'Total amount',
    'Бонус' => 'Bonus',
    'Токены' => 'Tokens',
    'Регистраций сегодня' => 'Registrations today',
    'Всего партнеров' => 'Total partners',
    'Обратная связь' => 'Feedback',
    'Мой профиль' => 'My profile',
    'Главная' => 'Main',
    'Логин' => 'Login',
    'Регистрация' => 'Signup',
    'Мои рефералы' => 'My referrals'
];
