<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Добро пожаловать' => 'Welcome!',
    'У вас нет прав!' => 'You have not right!',
    'Эта страница не существует!' => 'This page is not existed!',
    'Запись добавлена!' => 'New record!',
    'Ваш статус <span class="status_view">активен</span>!' => 'Your status <span class="status_view">is activated</span>!',
    'Ваш статус <span class="status_view">не активен</span>!' => 'Your status <span class="status_view">is not activated</span>!',
    'Страница не найдена!' => 'Page is not found!!',
    'Спонсора нет!' => 'This sponsor is not existed!',
    'Запись обновлена!' => 'Record is updated!',
    'Ошибка!' => 'Failure!',
    'Platform activated - Активация платформы!' => 'Platform is activated!',
    'Партнер активирован!' => 'Partner is activated!',
    'Вы зарегистрированы! Можете зайти в Личный Кабинет здесь' => 'You are registered! This link to your backoffice',
    'Вы зарегистрированы!' => 'You are registered!',
    'Запись удалена!' => 'Record is deleted!',
    'Такой страницы не существует!' => 'This page is not existed!',
    'Тема: Подтверждение регистрации' => 'Subject: Registration confirm',
    'Вы зарегистрированы! Подверждение регистрации отправлено вам на почту.' => 'You are registered! Confirmation is send to your email.',
    'Вы уже зарегистрированы!' => 'Already, you are registered!',
    'Вы прошли проверку!' => 'You passed the test!',
    'Пароль изменен!' => 'Passwod is changed!',
    'Это поле должно быть заполнено!' => 'This field must be filled!',
    'Введенны неправильные символы!' => 'Incorrect symbols!',
    'Рассылка создана!' => 'Mailing is created!',
    'Запрос на вывод совершен!' => 'Withdrawal request is done!',
    'Партнер добавлен' => 'Partner is added',
    'Партнеры добавлен' => 'Partners is added',
    'Демо структура создана!' => 'Demo structure is created!',
    'Список обновлен!' => 'The list is renewed!',
    'Ваше сообщение отправлено!' => 'Your message is send!',
    'Вы активированы!' => 'You are activated!',
];
